In [26]:
#1
lst = []
n = int(input("Enter number of elements : "))
for i in range(0, n ):
        for j in range (0, i+1):
            print("*", end=" ")
        print("\r")

Enter number of elements : 4
*
* *
* * *
* * * *

In [29]:
#1
n = int(input("Enter number of elements : "))
for i in range(0, n):
        for j in range (0, i+1):
            print("*", end=" ")
        print("\r")

Enter number of elements : 5
*
* *
* * *
* * * *
* * * * *

In [7]:
#3
dict1={
    'Bat':18,
    'Oyun':22,
    'Dulam':21,
    'Suren':20
}
key_max = max(dict1.keys(), key=(lambda k: dict1[k]))
key_min = min(dict1.keys(), key=(lambda k: dict1[k]))

print('Maximum Value: ',dict1.get(key_max))
print('Minimum Value: ',dict1.get(key_min))

Maximum Value:  22
Minimum Value:  18

In [16]:
#3
your_dictionary={
    'Bat':18,
    'Oyun':22,
    'Dulam':21,
    'Suren':20
}

new_maximum_val = max(your_dictionary.keys(), key=(lambda new_k: your_dictionary[new_k]))
print('Maximum Value: ',your_dictionary[new_maximum_val])
new_minimum_val = min(your_dictionary.keys(), key=(lambda new_k: your_dictionary[new_k]))
print('Minimum Value: ',your_dictionary[new_minimum_val])

Maximum Value:  22
Minimum Value:  18

Sum =  499500

In [2]:
#3
dict1={
    'Bat':18,
    'Oyun':22,
    'Dulam':21,
    'Suren':20
}


best_key = min(dict1, key=dict1.get)
best_key1 = max(dict1, key=dict1.get)
print(best_key)
print(best_key1)

Bat
Oyun

In [22]:
#4
sum=0
import numpy as np
data1=np.arange(1000)
arr1=np.array(data1)
arr1
for i in range(1000):
    if (i % 3 == 0 and i % 7 == 0):
        print(i)
        
        sum += int (i)
print("Sum = ",sum)

0
21
42
63
84
105
126
147
168
189
210
231
252
273
294
315
336
357
378
399
420
441
462
483
504
525
546
567
588
609
630
651
672
693
714
735
756
777
798
819
840
861
882
903
924
945
966
987
Sum =  23688

In [23]:
#4
sum=0
import numpy as np
data1=np.arange(1000)
arr1=np.array(data1)
arr1
for i in range(1000):
    if (i % 3 == 0 or i % 7 == 0):
        print(i)
        
        sum += int (i)
print("Sum = ",sum)

0
3
6
7
9
12
14
15
18
21
24
27
28
30
33
35
36
39
42
45
48
49
51
54
56
57
60
63
66
69
70
72
75
77
78
81
84
87
90
91
93
96
98
99
102
105
108
111
112
114
117
119
120
123
126
129
132
133
135
138
140
141
144
147
150
153
154
156
159
161
162
165
168
171
174
175
177
180
182
183
186
189
192
195
196
198
201
203
204
207
210
213
216
217
219
222
224
225
228
231
234
237
238
240
243
245
246
249
252
255
258
259
261
264
266
267
270
273
276
279
280
282
285
287
288
291
294
297
300
301
303
306
308
309
312
315
318
321
322
324
327
329
330
333
336
339
342
343
345
348
350
351
354
357
360
363
364
366
369
371
372
375
378
381
384
385
387
390
392
393
396
399
402
405
406
408
411
413
414
417
420
423
426
427
429
432
434
435
438
441
444
447
448
450
453
455
456
459
462
465
468
469
471
474
476
477
480
483
486
489
490
492
495
497
498
501
504
507
510
511
513
516
518
519
522
525
528
531
532
534
537
539
540
543
546
549
552
553
555
558
560
561
564
567
570
573
574
576
579
581
582
585
588
591
594
595
597
600
602
603
606
609
612
615
616
618
621
623
624
627
630
633
636
637
639
642
644
645
648
651
654
657
658
660
663
665
666
669
672
675
678
679
681
684
686
687
690
693
696
699
700
702
705
707
708
711
714
717
720
721
723
726
728
729
732
735
738
741
742
744
747
749
750
753
756
759
762
763
765
768
770
771
774
777
780
783
784
786
789
791
792
795
798
801
804
805
807
810
812
813
816
819
822
825
826
828
831
833
834
837
840
843
846
847
849
852
854
855
858
861
864
867
868
870
873
875
876
879
882
885
888
889
891
894
896
897
900
903
906
909
910
912
915
917
918
921
924
927
930
931
933
936
938
939
942
945
948
951
952
954
957
959
960
963
966
969
972
973
975
978
980
981
984
987
990
993
994
996
999
Sum =  214216

Enter number of elements : 5

Enter the numbers : 6

List is -  [6]